### ISSUE TITLE
Submenu items may be moved to the top

### ISSUE THREAD

**Issue by knutsp** [voldemortensen/menu-customizer#82]
When they are moved all the way to the top position, as the first item in a menu, they look orphaned. Luckily, after save, and re-entering the customizer or going to Appearance - Menus, they become top level items.

Suggestions, either:
* Only allow top level items to be moved from position 2 to position 1
* When a non-top level item is moved to the top, make it a top level item

By moving I mean both the arrows and dragging.

**Comment by westonruter** [comment]
This should be fixed by #63.

**Comment by designsimply** [comment]
@knutsp, thanks for reporting this!

I <em>think</em>: #63 moved to #99 then moved to #73 and is now merged.

My testing steps:

1. Update to the latest core trunk and plugin code. (I used WP 4.3-alpha-32775 and Menu Customizer plugin 0.6-cef7fbc.)
1. Go to Appearance > Customize > Menus and open an existing menu (or create one) that has submenu items in it
1. Drag one of the submenu items from it's current position to the top position as the first menu item

<stropng>Result:</strong> I was able to drag a submenu into the top position as the first item in a menu without any problems.

I am closing this issue, but please re-open if you test again and find the problem is still happening.

**Comment by knutsp** [comment]
This is changed, but not fixed.

Now, when I drag an 2nd level item to the top it becomes 1st level, it seems, at least visually. But then it becomes "untouchable" when using the arrows. Does not respond to arrow clicking. If I drag i back down, it later behaves normal to the arrows again.

It's necessary to decide how to handle dragging a not 1st level item to the top, or above it's current parent. Allow it and promote it to 1st level, or not allow it at all. The first seems to be what is the policy attempted, but it seems the underlying properties still regards such an item (2nd lever dragged to top) as still 2nd level, even if it displays as 1st level (leftmost). It seems to be inconsistent with itself, and stuck if I then try the arrows instead of mouse dragging.

Menu Customizer: 0.6-20150615
WordPress: 4.3-alpha-32775

**Comment by knutsp** [comment]
Steps to reproduce:
Initially, set up:
A
B
C

Move B to 2nd level:
A
    B
C

Drag B to top.
B
A
C

Click Reorder
Click the down arrow on B: Nothing happens. Try other arrows, nothing happens as expected, but they should all be shadowed

Drag B down below A:
A
    B
C

Try the up arrow on B. Nothing happens, as expected.
Try the left or down arrow on B, and it moves as expected. Move back to pos 2, level 2 (child of A)

Repeat form start and observe the bug is consistent.

**Comment by westonruter** [comment]
The keyboard-accessible arrows are mostly broken in the current plugin release. I have a re-implementation in #112 which might fix the bugs here. Can you try checking out that branch and see if it works? Otherwise, it's being reviewed by others on the team and should be merged in the next 12 hours, so you could test again fro the next plugin release.

**Comment by knutsp** [comment]
I am not using the keyboard at all. Clicking on arrows by mouse.

**Comment by designsimply** [comment]
By keyboard-accessible arrows, he means the ones that show up when you click "Reorder." You can click on them using either your mouse or your keyboard. In any case, an update was made to fix them. Can you try testing again?

**Comment by knutsp** [comment]
Appears fixed in Menu Customizer 0.6-20150616.
Excellent!

**Comment by designsimply** [comment]
Thanks so much for testing!
